### ISSUE TITLE
dataset importing across repos

### ISSUE THREAD

**Issue by mithilaunkule** [Bioforest-project/inventories#14]
If we are using the same datasets (located in the path: inventories -> data -> raw_data), how do we call them in codes in other repos, specially as the path before the inventories folder are different for each of us? (In the same repo, I'm using the function "here", but please suggest if there is a better way)

**Comment by sylvainschmitt** [comment]
We should not!

I made this only once to extract taxonomy for the species repo but we should avoid doing it. This was just a temporary way to do it before getting the species raw data. Anyhow, for the moment I can keep a relative path. We can imagine that everybody will have the same parent folders for the three repos. In that case we can use "../" to point the parent folders and accessing the raw data from inventories would simply be "../inventories/data/raw/data/". I'll make the changes asap. But this should be avoided whenever possible and the data are not big and could be duplicated per repo if needed.

**Comment by GeraldineDerroire** [comment]
> If we are using the same datasets (located in the path: inventories -> data -> raw_data), how do we call them in codes in other repos, specially as the path before the inventories folder are different for each of us? (In the same repo, I'm using the function "here", but please suggest if there is a better way)

In addition to Sylvain's answer, as we are using Rstudio project, we should all have the same path (relative to the root of the repo),  when the data we call are in the same repo at least. So no need to use "here" I think
