### ISSUE TITLE
Share raw data

### ISSUE THREAD

**Issue by GeraldineDerroire** [Bioforest-project/inventories#4]
- [x] rename files consistently
- [x]  add version number
- [x] send files per site for version 1
- [ ] update and share new versions

**Comment by GeraldineDerroire** [comment]
@mithilaunkule : please give us the raw data so that we can start coding. Please give us also the metadata

**Comment by sylvainschmitt** [comment]
@GeraldineDerroire suggested a Zenodo depot for sharing raw data, but if they risk to change a lot I would suggest something simpler such as a private drive or simply an archive shared by email. However, if we think we have a st of raw data that won't change much, I agree for a closed / private Zenodo repo.

**Comment by cpiponiot** [comment]
I would suggest just sharing the raw data via a data transfer link; but we might want to make sure that the site PIs are happy to share their raw data with all of us. We probably don't need all the datasets to develop the codes. Adapting the codes for all the other sites will then require a bit more work, but shouldn't take too long as it would only involve adding a few lines of code at the beginning of the script (e.g. removing incomplete inventories, reformatting some columns, etc.). This could be done by Mithila or someone else who has the full dataset.

**Comment by mithilaunkule** [comment]
> I would suggest just sharing the raw data via a data transfer link; but we might want to make sure that the site PIs are happy to share their raw data with all of us. We probably don't need all the datasets to develop the codes. Adapting the codes for all the other sites will then require a bit more work, but shouldn't take too long as it would only involve adding a few lines of code at the beginning of the script (e.g. removing incomplete inventories, reformatting some columns, etc.). This could be done by Mithila or someone else who has the full dataset.

I agree with this as well. I can re-share a dataset if something changes, which will also helkp us keep track. I can name them by version numbers to make the identification easy.

**Comment by mithilaunkule** [comment]
> > I would suggest just sharing the raw data via a data transfer link; but we might want to make sure that the site PIs are happy to share their raw data with all of us. We probably don't need all the datasets to develop the codes. Adapting the codes for all the other sites will then require a bit more work, but shouldn't take too long as it would only involve adding a few lines of code at the beginning of the script (e.g. removing incomplete inventories, reformatting some columns, etc.). This could be done by Mithila or someone else who has the full dataset.
> 
> I agree with this approach. I would only suggest one more thing if we use data transfer link: I would suggest to use versioning of the raw data to help dev & debug. Indeed a version number could be added as a header, in file names or as an accompanying dummy file and listed in the raw data readme to indicate to co-developers that they may not have the correct version to get the code working. And additionally thus a NEWS.md could be used in the raw data folder if it make sense to track the changes between the different versions of the raw data. Let me know if it's not clear enough.

Everything is clear, but I am not sure I understand the NEWS.md file. Does that mean I just add information suhc asold file name, any changes made, date of changes, and new file name, like a README?

**Comment by sylvainschmitt** [comment]
> > > I would suggest just sharing the raw data via a data transfer link; but we might want to make sure that the site PIs are happy to share their raw data with all of us. We probably don't need all the datasets to develop the codes. Adapting the codes for all the other sites will then require a bit more work, but shouldn't take too long as it would only involve adding a few lines of code at the beginning of the script (e.g. removing incomplete inventories, reformatting some columns, etc.). This could be done by Mithila or someone else who has the full dataset.
> > 
> > 
> > I agree with this approach. I would only suggest one more thing if we use data transfer link: I would suggest to use versioning of the raw data to help dev & debug. Indeed a version number could be added as a header, in file names or as an accompanying dummy file and listed in the raw data readme to indicate to co-developers that they may not have the correct version to get the code working. And additionally thus a NEWS.md could be used in the raw data folder if it make sense to track the changes between the different versions of the raw data. Let me know if it's not clear enough.
> 
> Everything is clear, but I am not sure I understand the NEWS.md file. Does that mean I just add information suhc asold file name, any changes made, date of changes, and new file name, like a README?

The idea is that maybe you will share with use a first version of raw data that we may call 0.1.0 (or a simpler convention). In the NEWS.md you will thus say "inventories raw data 0.1.0: init / first share" or something like that. And then I don't know, maybe we discover that you add a column missing so you share with us a new version, e.g. 0.2.0. In the NEWS.md you could thus say "inventories raw data 0.2.0: adding column XXX". It's just to keep track of the different version shared especially if we use data transfer link between us. @mithilaunkule , is it clearer?

**Comment by mithilaunkule** [comment]
> > > > I would suggest just sharing the raw data via a data transfer link; but we might want to make sure that the site PIs are happy to share their raw data with all of us. We probably don't need all the datasets to develop the codes. Adapting the codes for all the other sites will then require a bit more work, but shouldn't take too long as it would only involve adding a few lines of code at the beginning of the script (e.g. removing incomplete inventories, reformatting some columns, etc.). This could be done by Mithila or someone else who has the full dataset.
> > > 
> > > 
> > > I agree with this approach. I would only suggest one more thing if we use data transfer link: I would suggest to use versioning of the raw data to help dev & debug. Indeed a version number could be added as a header, in file names or as an accompanying dummy file and listed in the raw data readme to indicate to co-developers that they may not have the correct version to get the code working. And additionally thus a NEWS.md could be used in the raw data folder if it make sense to track the changes between the different versions of the raw data. Let me know if it's not clear enough.
> > 
> > 
> > Everything is clear, but I am not sure I understand the NEWS.md file. Does that mean I just add information suhc asold file name, any changes made, date of changes, and new file name, like a README?
> 
> The idea is that maybe you will share with use a first version of raw data that we may call 0.1.0 (or a simpler convention). In the NEWS.md you will thus say "inventories raw data 0.1.0: init / first share" or something like that. And then I don't know, maybe we discover that you add a column missing so you share with us a new version, e.g. 0.2.0. In the NEWS.md you could thus say "inventories raw data 0.2.0: adding column XXX". It's just to keep track of the different version shared especially if we use data transfer link between us. @mithilaunkule , is it clearer?

Yes got it, thanks!

**Comment by GeraldineDerroire** [comment]
hi all, I agree with all of the above, including the need to do clear versionning.

**Comment by mithilaunkule** [comment]
Question for all: Should I send 1 file per site, or as I received them? A few sites have sent me different files for the different plots/treatments.

**Comment by sylvainschmitt** [comment]
> @mithilaunkule , thanks for sharing the first version of the data. However, using them to generate raw species list I found two issues:
> 
>     * Moju has only taxonomic data in `VernName`
> 
>     * Mbaiki has only taxonomic data in `ScientificName`
> 
> 
> How should we deal with them? Should we drop them for now?

This also concern Kibale and Peteco

**Comment by GeraldineDerroire** [comment]
> @GeraldineDerroire for the ONF plot, how should we name the site: Manare? St Lavilette? Regina st georges?

The site name is Regina St Georges (for the two Manaré plots and the Saut Lavilette one).

Note that there is also two other sites from the ONF: BAFOG and Montagne Tortue

**Comment by GeraldineDerroire** [comment]
> > Question for all: Should I send 1 file per site, or as I received them? A few sites have sent me different files for the different plots/treatments.
> 
> I think the best is to be the closest to what PIs will have, but maybe others will disagree. Anyhow, I think you can make a choice and start sharing it as version 0.1.0. If people disagree, you can share it again as a new version.

Whatever we choose, I think that we should do the data preparation (so all the step in the inventory repo) at the site level. So if the PI provides several files per sites, the first step should be to concatenate them.

**Comment by mithilaunkule** [comment]
> @mithilaunkule , thanks for sharing the first version of the data. However, using them to generate raw species list I found two issues:
> 
>     * Moju has only taxonomic data in `VernName`
> 
>     * Mbaiki has only taxonomic data in `ScientificName`
> 
> 
> How should we deal with them? Should we drop them for now?

Yes these are datasets as the PIs shared with me. The files are not always consistent for the different sites if the PIs harmonize them. I usually check it manually as that it the only way to ensure we have the same info across datasets. Is there a better way to do it?

**Comment by sylvainschmitt** [comment]
> > @mithilaunkule , thanks for sharing the first version of the data. However, using them to generate raw species list I found two issues:
> > ```
> > * Moju has only taxonomic data in `VernName`
> > 
> > * Mbaiki has only taxonomic data in `ScientificName`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How should we deal with them? Should we drop them for now?
> 
> This also concern Kibale, Peteco, Lesong, Misiones, Sg Lalang, and Ulu Muda.

Please can we address this before closing the issue?

**Comment by sylvainschmitt** [comment]
> > > @mithilaunkule , thanks for sharing the first version of the data. However, using them to generate raw species list I found two issues:
> > > ```
> > > * Moju has only taxonomic data in `VernName`
> > > 
> > > * Mbaiki has only taxonomic data in `ScientificName`
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > How should we deal with them? Should we drop them for now?
> > 
> > 
> > This also concern Kibale, Peteco, Lesong, Misiones, Sg Lalang, and Ulu Muda.
> 
> Please can we address this before closing the issue?

Ok I just discussed it with Camille and for taxonomy we agreed that we will have an additional separate taxonomy cleaning script with some site specific tweaking. This also concerns https://github.com/Bioforest-project/species/issues/4.
